Финальное задание спринта 7
zolotyh-dk/java-kanban pull request #4
Opened 2024-04-21 09:33 UTC by zolotyh-dk

### Добавлена новая реализация менеджера задач `FileBackedTaskManager`

- Новый менеджер задач дополняет функции `InMemoryHistoryManager` возможностью сохранения и восстановления задач из .csv файла
- Добавлен новый тестовый класс `FileBackedTaskManager`, который наследуется от `InMemoryTaskManagerTest` и дополняет его тестами на корректную работу с файлом бэкапа
- Класс `Task` теперь реализует интерфейс `Comparable` для сортировки по ID перед записью задач в файл. Это позволяет при десериализации гарантировать что всем типам задач присвоятся старые ID.

2024-04-22 06:11 UTC, YazykovMikhail reviewed
В класс Manages стоит обновить работу поумолчнию, теперь она будет работать через файл:

	public static TaskManager getDefault() {
		return new FileBackedTaskManager(new File("resources/task.csv"));
	}

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +    private void save() {
В целом ок, но есть пару моментов
1) '\n' - в разных операционных системах перевод строки пишется по разному
2) сотировать не обязательно, генерировать id при считываении из истории не нужно, ведь некоторые задчи могли быть удали и в истории было бы 1,2,5,7 если генерировать id то восстановится не актуальными занчениями
3) Лучше использовать буферизацию для записи, будет экономить ресурсы

Вот так можно улучшить:
```

	protected void save() {
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
			writer.write(CSVTaskFormat.getHeader());
			writer.newLine();

			for (Map.Entry<Integer, Task> entry : tasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Subtask> entry : subtasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Epic> entry : epics.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			writer.newLine();
		} catch (IOException e) {
			throw new ManagerSaveException("Can't save to file: " + file.getName(), e);
		}
	}
```

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/task/Epic.java
Стоит все поля в классе сделать protected, что бы был прямой доступ из класса наслденика

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +            if (task instanceof Epic) {
Не зря ты вводил типы задач, используй их

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +                taskManager.addNewEpic((Epic) task);
Как уже скзаал при сохранении, методы добавления использовать не стоит пр ивосстанволении, потому что методы гененируют новые id, а нам неоходимо именно восстановить текущие. Непосредтсвеннно добавляй сразу в хранилизе считанные задачи

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +
И нужно восстанавливать счетчик id, как ты уже понял задач может быть сохранено в файл 10, но последний идентификатор может быть 50, потому что в овремя работы приложения задачи удалялись.

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File file) {
Сначала прочитай все комментари к методу, 


СПОЙДЕР:
```
public static FileBackedTaskManager loadFromFile(File file) {
		final FileBackedTaskManager taskManager = new FileBackedTaskManager(file);
		try {
			final String csv = Files.readString(file.toPath());
			final String[] lines = csv.split(System.lineSeparator());
			int generatorId = 0;
			for (int i = 1; i < lines.length; i++) {
				String line = lines[i];
				if (line.isEmpty()) {
					break;
				}
				final Task task = CSVTaskFormat.fromString(line);
				final int id = task.getId();
				if (id > generatorId) {
					generatorId = id;
				}
				taskManager.addAnyTask(task);
			}
			for (Map.Entry<Integer, Subtask> e : taskManager.subtasks.entrySet()) {
				final Subtask subtask = e.getValue();
				final Epic epic = taskManager.epics.get(subtask.getEpicId());
				epic.addSubtaskId(subtask.getId());
			}
			taskManager.generatorId = generatorId;
		} catch (IOException e) {
			throw new ManagerSaveException("Can't read form file: " + file.getName(), e);
		}
		return taskManager;
	}
```

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +                writer.write(all.get(i).toString());
Стоит использовать отдельны метод toString, не зря в задании говорится : 
"Напишите метод сохранения задачи в строку"
Метод toString которые есть в каждом обьекте, он используется внутри самой джавы для многих вещей, а тут конкретно бизнес процесс, не стоит их мешать между собой.

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +                writer.write(all.get(i).toString());
Очень просто метод:
```
public static String toString(Task task) {
		return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," + task.getDescription() + "," + (task.getType().equals(TaskType.SUBTASK) ? task.getEpicId() : "");
	}
```

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +    private static Task fromString(String value) {
Стоит все методы из пункта задания:
"Как сохранять задачи в файл и считывать их из него" вынести в утилитный класс:

CSVTaskFormat и выызвать от туда статические методы

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +        final String heading = "id,type,name,status,description,epic";
Тоже стоит вынести в утилитный класс CSVTaskFormat
Ввиде константы или метода:
```
	public static String getHeader() {
		return "id,type,name,status,description,epic";
	}

```

2024-04-22 06:11 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/task/Task.java
> +public class Task implements Comparable<Task> {
Стоит добавить или поле Type type или в каждую задачу просто один метод:

```
	public TaskType getType() {
		return TaskType.TASK;
	}
```
Который будет возвращать конкретный тип задачи

2024-04-22 06:13 UTC, YazykovMikhail requested changes
Вообще хорошо, есть небольшие моменты которые стоит поправить

2024-04-23 11:40 UTC, zolotyh-dk commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +    private void save() {
Переделал метод `save()` с использованием буферизации, сортировку убрал, '\n' везде по коду заменил на `BufferedWriter.newLine()` и `System.lineSeparator()`

2024-04-23 11:41 UTC, zolotyh-dk commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +        final String heading = "id,type,name,status,description,epic";
Вынес в `CSVTaskFormat`

2024-04-23 11:45 UTC, zolotyh-dk commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +                writer.write(all.get(i).toString());
Добавил метод `toString()` в `CSVTaskFormat`.  Предложенный вариант доработал, чтобы запятая в конце строки ставилась и для подзадач тоже + добавил каст до эпика перед `task.getEpicId()`

2024-04-23 11:47 UTC, zolotyh-dk commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +            if (task instanceof Epic) {
Вынес определение типа и добавление в хранилища в отдельный метод `void addAnyTask(Task task)`

2024-04-23 11:48 UTC, zolotyh-dk commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/FileBackedTaskManager.java
> +                taskManager.addNewEpic((Epic) task);
Исправил, для прямого доступа к хранилищам сделал поля protected

2024-04-23 11:49 UTC, zolotyh-dk commented on src/main/ru/yandex/javacourse/zolotyh/schedule/task/Task.java
> +public class Task implements Comparable<Task> {
Добавил методы в `Task` и переопределил в наследниках

2024-04-23 15:31 UTC, YazykovMikhail approved these changes

2024-05-02 08:06 UTC, merged