Финальное задание спринта 8
zolotyh-dk/java-kanban pull request #5
Opened 2024-05-07 13:34 UTC by zolotyh-dk

1. Для задач добавлены продолжительность и дата старта
2. Добавлен выводим списка задач в порядке даты старта
3. Добавлена функциональность для определения пересечения времени выполнения задач
- методом наложения отрезков
- поиском временных интервалов в хеш-таблице
4. Циклы foreach заменены на использование Stream API
5. Для `InMemoryTaskManagerTest `и `FileBackedTaskManagerTest `создан базовый класс. Для удобства тестирования создан класс `TaskUtil`
6. Методы получения задач по id теперь возвращают `Optional`

2024-05-07 14:10 UTC, YazykovMikhail requested changes

2024-05-07 14:10 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/task_manager/InMemoryTaskManager.java
> +    public Optional<Task> getTaskById(int id) {
из метода стоит возвращать уже саму задачу, а не Optional
Тогда стоит определится выбрасывать исключение, если null или возвращать или возвращать null

2024-05-07 14:10 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/task_manager/InMemoryTaskManager.java
> +    public Optional<Task> getTaskById(int id) {
Если возвращать null, то как будуто тут использование не оправдано, ведь при добавлении в историю проверяется на null и если null ничего не происходит.

2024-05-07 14:10 UTC, YazykovMikhail commented on test/ru/yandex/javacourse/zolotyh/schedule/manager/task_manager/FileBackedTaskManagerTest.java
> +package ru.yandex.javacourse.zolotyh.schedule.manager.task_manager;
назов папку просто task по поути и так будет понятно что это 
ru.yandex.javacourse.zolotyh.schedule.manager.task
аналогично для истории
ru.yandex.javacourse.zolotyh.schedule.manager.history

2024-05-07 14:10 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/history_manager/InMemoryHistoryManager.java
Как то пропустилось, в методе add все таки должна быть эта проверка в самом начале:
    public void add(Task task) {
        if (task == null) {
            return;
        }

2024-05-07 14:10 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/util/TimeUtil.java
> +    public static class TimeSlotTable {
Лучше вынести 
 private final Map<LocalDateTime, Boolean> slots;
  в InMemoryTaskManager  и там проводить расчеты, статическое состояние не совсме подходит для данного процесса, например захотел какой то новый отдел сделать себе TaskManager создал новый экземпляр, а у вас получился один календарь на двоих. 
  
  Или же сделать отдельный сервис для хранения 
   private final Map<LocalDateTime, Boolean> slots;
   и методов для работы.

2024-05-07 14:10 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/util/TimeUtil.java
> +    public static class TimeSlotTable {
И утилитный класс не должен хранить состояние, его дело что то посчитывать/выдавать результат на основе входящих данных

2024-05-07 14:10 UTC, YazykovMikhail commented on src/main/ru/yandex/javacourse/zolotyh/schedule/util/TimeUtil.java
> +public class TimeUtil {
В связи с комментариями ниже, встает вопрос необходимости в целом этого утилитного класса, тут остаются 3 метода, которые не универсальные, а заточены под конкретные поля и задачи. 
Лучще их вынести в локальные методы

2024-05-07 19:42 UTC, zolotyh-dk commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/task_manager/InMemoryTaskManager.java
> +    public Optional<Task> getTaskById(int id) {
Переделал, возвращаю саму задачу. `Optional` обрабатываю внутри метода и выбрасываю `NoSuchElementException`

2024-05-07 19:45 UTC, zolotyh-dk commented on src/main/ru/yandex/javacourse/zolotyh/schedule/manager/history_manager/InMemoryHistoryManager.java
Добавил проверку на `null`

2024-05-08 05:47 UTC, zolotyh-dk commented on test/ru/yandex/javacourse/zolotyh/schedule/manager/task_manager/FileBackedTaskManagerTest.java
> +package ru.yandex.javacourse.zolotyh.schedule.manager.task_manager;
Переименовал директории

2024-05-08 06:26 UTC, zolotyh-dk commented on src/main/ru/yandex/javacourse/zolotyh/schedule/util/TimeUtil.java
> +    public static class TimeSlotTable {
Перенес функциональность `TimeUtil` в методы `InMemoryTaskManager`

2024-05-08 13:41 UTC, YazykovMikhail approved these changes

2024-05-09 12:33 UTC, merged